action by shell

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -20,17 +20,17 @@ jobs:
         password: ${{ secrets.SSH_PASSWORD }}
         script: |
           cd /root/wonderland-backend
-
-          if ! git pull https://github.com/floatDreamWithSong/wonderland-backend.git main ; then
-            echo "Git pull failed"
-            exit 1
-          fi
+          sh deploy.sh
+          # if ! git pull https://github.com/floatDreamWithSong/wonderland-backend.git main ; then
+          #   echo "Git pull failed"
+          #   exit 1
+          # fi
           
           # 安装依赖并构建
-          npx pnpm install
-          NODE_ENV=production
-          npx prisma generate
-          npx prisma migrate deploy
-          npx pnpm build
+          # npx pnpm install
+          # NODE_ENV=production
+          # npx prisma generate
+          # npx prisma migrate deploy
+          # npx pnpm build
           # 使用PM2重启服务
-          npx pm2 restart wonderland-backend || npx pm2 start dist/main.js --name wonderland-backend
+          # npx pm2 restart wonderland-backend || npx pm2 start dist/main.js --name wonderland-backend
